name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Runs every day at midnight
  push:
    branches:
      - main  # Run workflow on push to main branch
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Generate snake commit animation
        uses: Platane/snk@master
        with:
          github_user_name: 3bdelmonem
          outputs: dist/snake.svg

      - name: Commit and push the generated snake.svg
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add -A
          git commit -m "Generate snake commit animation"
          git push
